package com.itheima;

import com.example.EnableHeaderConfig;
import com.example.HeaderConfig;
import com.example.MyImportSelector;
import com.example.TokenParser;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Import;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

//@ComponentScan({"com.example","com.itheima"})


//@Import({TokenParser.class}) //导入普通类，该类上面可以不用加任何注解，交给IOC容器管理



//@Import({HeaderConfig.class})  //导入配置类，交给IOC容器管理

//@Import({MyImportSelector.class})  //导入ImportSelector接口的实现类

@EnableHeaderConfig

@SpringBootApplication
public class SpringbootWebConfig2Application {

    public static void main(String[] args) {

        SpringApplication.run(SpringbootWebConfig2Application.class, args);
    }

}
