#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlia
    username: root
    password: 20021212

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#文件上传配置
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 100MB

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tPP9Eivi7KctDHgo3L2
    accessKeySecret: I6TXOYLRZxrm9yjcBhNZ8zLfmpFxr1
    bucketName: hmleadnews0809
#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug